name: flower_user_ui
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  camera: ^0.8.1+7
  connectivity: ^3.0.6
  crypt: ^4.0.1
  cupertino_icons: ^1.0.3
  dfunc: ^0.7.2
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_svg: ^0.22.0
  form_field_validator: ^1.1.0
  get_it: ^7.2.0
  im_stepper: ^0.1.3
  image_picker: ^0.8.3+2
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  kt_dart: ^0.9.1
  lint: ^1.5.3
  mockito: ^5.0.14
  pull_to_refresh: ^2.0.0
  sembast: ^3.1.0+2
  sembast_web: ^2.0.0+2
  shared_preferences: ^2.0.6
  supercharged: ^2.0.0
  supercharged_dart: ^2.0.0
  top_snackbar_flutter: ^1.0.0
  velocity_x: ^3.3.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "resources/images/icon.png"
  image_path_android: "resources/images/icon.png"
  adaptive_icon_background: "resources/images/gradient.png"
  adaptive_icon_foreground: "resources/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - resources/
    - resources/images/
  fonts:
    - family: Philosopher
      fonts:
        - asset: resources/fonts/Philosopher.ttf
    - family: SourceSansPro
      fonts:
        - asset: resources/fonts/SourceSansPro.ttf

  uses-material-design: true
