name: flower_user_ui
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  cached_network_image: ^3.1.0
  camera: ^0.8.1+7
  collection: ^1.15.0-nullsafety.4
  connectivity: ^3.0.6
  crypt: ^4.0.1
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  flex_color_scheme: ^3.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_svg: ^0.22.0
  form_field_validator: ^1.1.0
  get_it: ^7.2.0
  im_stepper: ^0.1.3
  image_picker: ^0.8.3+2
  infinite_scroll_pagination: ^3.1.0
  injectable: ^1.4.1
  intl: ^0.17.0
  kt_dart: ^0.9.1
  lint: ^1.5.3
  logger: ^1.0.0
  mockito: ^5.0.14
  pull_to_refresh: ^2.0.0
  sembast: ^3.1.0+2
  sembast_web: ^2.0.0+2
  shared_preferences: ^2.0.6
  stacked: ^2.2.3
  stacked_services: ^0.8.13
  supercharged: ^2.0.0
  supercharged_dart: ^2.0.0
  top_snackbar_flutter: ^1.0.0
  velocity_x: ^3.3.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/gradient.png"
  adaptive_icon_foreground: "assets/images/logo.png"

dev_dependencies:
  auto_route_generator: any
  build_runner: ^2.1.1
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1

flutter_gen:
  output: lib/presentation/utils
  line_length: 80

flutter:
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf

  uses-material-design: true
